const packageOption = (label, price, details) => ({ label, price, details });
const priceOption = (label, price) => ({ label, price });

export const homepageTreatments = [
  {
    id: "aloe-vera-massage",
    name: "Aloe Vera Massage",
    category: "massage",
    href: "/seminyak/sunburn-treatment",
    image: "/images/homepage/homepage-12.webp",
    desc: "A cooling full-body treatment that soothes the skin and supports gentle recovery.",
    options: [priceOption("1 Hour", "IDR 199K")],
  },
  {
    id: "aromatherapy-massage",
    name: "Aromatherapy Massage",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-5.webp",
    desc: "A gentle full-body treatment combining essential oils with slow and calming movements.",
    options: [priceOption("1 Hour", "IDR 169K"), priceOption("1.5 Hours", "IDR 239K"), priceOption("2 Hours", "IDR 339K")],
  },
  {
    id: "balinese-massage",
    name: "Balinese Massage",
    category: "massage",
    href: "/seminyak/balinese-massage",
    image: "/images/homepage/homepage-5.webp",
    desc: "A calming full-body treatment with steady pressure, gentle stretches, and aromatic oils.",
    options: [priceOption("1 Hour", "IDR 159K"), priceOption("1.5 Hours", "IDR 239K"), priceOption("2 Hours", "IDR 330K"), priceOption("1 Hour with Aloe Vera", "IDR 195K")],
  },
  {
    id: "back-massage",
    name: "Back Massage",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-10.webp",
    desc: "A targeted upper-body treatment focused on easing tightness and restoring comfort.",
    options: [priceOption("30 Minutes", "IDR 90K"), priceOption("1 Hour", "IDR 169K"), priceOption("1.5 Hours", "IDR 259K"), priceOption("2 Hours", "IDR 339K")],
  },
  {
    id: "cellulite-massage",
    name: "Cellulite Massage",
    category: "massage",
    href: "/seminyak/cellulite-massage",
    image: "/images/homepage/homepage-17.webp",
    desc: "A targeted full-body treatment designed to stimulate circulation and improve skin tone.",
    options: [priceOption("1 Hour", "IDR 350K"), priceOption("1.5 Hours", "IDR 450K")],
  },
  {
    id: "deep-tissue-massage",
    name: "Deep Tissue Massage",
    category: "massage",
    href: "/seminyak/deep-tissue-massage",
    image: "/images/homepage/homepage-10.webp",
    desc: "A focused full-body treatment using deeper pressure to release knots and improve mobility.",
    options: [priceOption("1 Hour", "IDR 269K"), priceOption("1.5 Hours", "IDR 359K")],
  },
  {
    id: "four-hand-massage",
    name: "Four Hand Massage",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-21.webp",
    desc: "A synchronized full-body treatment delivered by two therapists working in harmony.",
    options: [priceOption("1 Hour", "IDR 339K"), priceOption("1.5 Hours", "IDR 499K"), priceOption("2 Hours", "IDR 669K")],
  },
  {
    id: "four-hand-warm-candle",
    name: "Four Hand Warm Candle",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-21.webp",
    desc: "A deeply relaxing treatment where two therapists work together using warmed oils.",
    options: [priceOption("1 Hour", "IDR 539K"), priceOption("1.5 Hours", "IDR 799K"), priceOption("2 Hours", "IDR 999K")],
  },
  {
    id: "foot-reflexology",
    name: "Foot Reflexology",
    category: "massage",
    href: "/seminyak/foot-reflexology",
    image: "/images/homepage/homepage-22.webp",
    desc: "A focused lower-body treatment applying pressure to reflex points on the feet.",
    options: [priceOption("30 Minutes", "IDR 99K"), priceOption("1 Hour", "IDR 169K"), priceOption("1.5 Hours", "IDR 239K")],
  },
  {
    id: "foot-massage",
    name: "Foot Massage",
    category: "massage",
    href: "/seminyak/foot-massage",
    image: "/images/homepage/homepage-18.webp",
    desc: "A focused massage on the soles, heels, and ankles to ease stiffness and restore comfort.",
    options: [priceOption("1 Hour", "IDR 159K"), priceOption("1.5 Hours", "IDR 239K"), priceOption("2 Hours", "IDR 330K")],
  },
  {
    id: "head-massage",
    name: "Head Massage",
    category: "massage",
    href: "/seminyak/head-massage",
    image: "/images/homepage/homepage-11.webp",
    desc: "A focused head massage that helps release built-up stress and quiet the mind.",
    options: [priceOption("1 Hour", "IDR 159K"), priceOption("1.5 Hours", "IDR 239K"), priceOption("2 Hours", "IDR 330K")],
  },
  {
    id: "herbal-massage",
    name: "Herbal Massage",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-16.webp",
    desc: "A comforting full-body treatment with herbal ingredients to support relaxation and circulation.",
    options: [priceOption("1 Hour", "IDR 199K"), priceOption("2 Hours", "IDR 399K")],
  },
  {
    id: "lymphatic-massage",
    name: "Lymphatic Massage",
    category: "massage",
    href: "/seminyak/lymphatic-massage",
    image: "/images/homepage/homepage-15.webp",
    desc: "A gentle full-body treatment that supports drainage and healthy circulation.",
    options: [priceOption("1 Hour", "IDR 300K"), priceOption("1.5 Hours", "IDR 440K"), priceOption("2 Hours", "IDR 580K")],
  },
  {
    id: "organic-warm-candle-oil-massage",
    name: "Organic Warm Candle Oil Massage",
    category: "massage",
    href: "/contact",
    image: "/images/homepage/homepage-7.webp",
    desc: "A warming full-body treatment using natural oils to soften muscles and calm the body.",
    options: [priceOption("1 Hour", "IDR 269K"), priceOption("1.5 Hours", "IDR 399K"), priceOption("2 Hours", "IDR 499K")],
  },
  {
    id: "shiatsu-massage",
    name: "Shiatsu Massage",
    category: "massage",
    href: "/seminyak/shiatsu-massage",
    image: "/images/homepage/homepage-27.webp",
    desc: "An oil-free full-body treatment using Japanese pressure-point techniques to ease tension.",
    options: [priceOption("30 Minutes", "IDR 119K"), priceOption("1 Hour", "IDR 219K"), priceOption("1.5 Hours", "IDR 329K")],
  },
  {
    id: "sports-massage",
    name: "Sports Massage",
    category: "massage",
    href: "/seminyak/sports-massage",
    image: "/images/homepage/homepage-8.webp",
    desc: "A targeted full-body treatment to ease soreness, reduce stiffness, and support recovery.",
    options: [priceOption("1 Hour", "IDR 269K"), priceOption("1.5 Hours", "IDR 359K")],
  },
  {
    id: "thai-massage",
    name: "Thai Massage",
    category: "massage",
    href: "/seminyak/thai-massage",
    image: "/images/homepage/homepage-20.webp",
    desc: "An oil-free full-body treatment combining assisted stretches and rhythmic pressure.",
    options: [priceOption("30 Minutes", "IDR 133K"), priceOption("1 Hour", "IDR 259K"), priceOption("1.5 Hours", "IDR 379K")],
  },
  {
    id: "traditional-massage",
    name: "Traditional Massage",
    category: "massage",
    href: "/seminyak/traditional-massage",
    image: "/images/homepage/homepage-16.webp",
    desc: "A firmer full-body treatment using deeper pressure to release muscle tension.",
    options: [priceOption("30 Minutes", "IDR 90K"), priceOption("1 Hour", "IDR 169K"), priceOption("1.5 Hours", "IDR 259K"), priceOption("2 Hours", "IDR 339K")],
  },
  {
    id: "virgin-cold-press-coconut-oil-massage",
    name: "Virgin Cold-Press Coconut Oil Massage",
    category: "massage",
    href: "/seminyak/virgin-coconut-oil-massage",
    image: "/images/homepage/homepage-25.webp",
    desc: "A nourishing full-body treatment using pure coconut oil to promote deep relaxation.",
    options: [priceOption("1 Hour", "IDR 300K"), priceOption("1.5 Hours", "IDR 440K"), priceOption("2 Hours", "IDR 580K")],
  },
  {
    id: "warm-stone-massage",
    name: "Warm Stone Massage",
    category: "massage",
    href: "/seminyak/hot-stone-massage",
    image: "/images/homepage/homepage-7.webp",
    desc: "A soothing full-body treatment using heated stones to relax muscles and support circulation.",
    options: [priceOption("1.5 Hours", "IDR 299K"), priceOption("2 Hours", "IDR 439K")],
  },
  {
    id: "bali-moon-tea-tree-facial",
    name: "Bali Moon Tea Tree Facial",
    category: "beauty",
    href: "/seminyak/bali-moon-facial",
    image: "/images/homepage/homepage-9.webp",
    desc: "A purifying facial treatment for oily or blemish-prone skin using clay and tea tree care.",
    options: [packageOption("Facial Treatment", "IDR 196K", ["Helps control excess oil", "Supports clearer-looking skin", "Calms and refreshes the face", "Maintains healthy hydration"])],
  },
  {
    id: "bali-moon-gold-facial",
    name: "Bali Moon Gold Facial",
    category: "beauty",
    href: "/seminyak/bali-moon-facial",
    image: "/images/homepage/homepage-9.webp",
    desc: "A premium facial treatment using gold and argan oil to support radiance and skin firmness.",
    options: [packageOption("Facial Treatment", "IDR 269K", ["Boosts natural glow", "Improves skin smoothness and elasticity", "Deeply moisturizes", "Revives overall skin vitality"])],
  },
  {
    id: "biokos-facial",
    name: "Biokos Facial",
    category: "beauty",
    href: "/seminyak/bali-moon-facial",
    image: "/images/homepage/homepage-9.webp",
    desc: "A custom facial treatment for dry, normal, or oily skin, including a facial massage and mask.",
    options: [priceOption("Biokos", "IDR 179K"), priceOption("Mustika Ratu", "IDR 169K"), priceOption("Sari Ayu", "IDR 169K"), priceOption("Viva", "IDR 169K")],
  },
  {
    id: "body-scrub",
    name: "Body Scrub",
    category: "beauty",
    href: "/seminyak/body-scrub",
    image: "/images/homepage/homepage-13.webp",
    desc: "A gentle exfoliation treatment to refresh the skin and leave it smooth and clean.",
    options: [priceOption("Chocolate", "IDR 169K"), priceOption("Coconut", "IDR 169K"), priceOption("Strawberry", "IDR 169K"), priceOption("Bengkoang", "IDR 169K"), priceOption("Jasmine", "IDR 169K"), priceOption("Green Tea", "IDR 169K"), priceOption("Spa Sari", "IDR 169K")],
  },
  {
    id: "ear-candle",
    name: "Ear Candle",
    category: "beauty",
    href: "/seminyak/ear-candle",
    image: "/images/homepage/homepage-14.webp",
    desc: "A traditional ear candle treatment focused on comfort and gentle relaxation.",
    options: [priceOption("30 Minutes", "IDR 159K")],
  },
  {
    id: "eyelash",
    name: "Eyelash",
    category: "beauty",
    href: null,
    image: "/images/homepage/homepage-23.webp",
    desc: "A simple beauty treatment designed to enhance lash length and fullness.",
    options: [priceOption("Normal Eyelash", "IDR 299K"), priceOption("Volume", "IDR 359K"), priceOption("Mega Volume", "IDR 399K")],
  },
  {
    id: "hair-cream-bath",
    name: "Hair Cream Bath",
    category: "beauty",
    href: "/seminyak/hair-creambath",
    image: "/images/homepage/homepage-6.webp",
    desc: "A nourishing hair treatment that cleanses, conditions, and relaxes the scalp.",
    options: [priceOption("Ginseng", "IDR 165K"), priceOption("Avocado", "IDR 165K"), priceOption("Aloe Vera", "IDR 165K"), priceOption("L'Oreal", "IDR 195K"), priceOption("NR", "IDR 165K"), priceOption("Hair Mask", "IDR 165K")],
  },
  {
    id: "manicure-pedicure",
    name: "Manicure Pedicure",
    category: "beauty",
    href: "/seminyak/manicure-pedicure",
    image: "/images/homepage/homepage-19.webp",
    desc: "A complete hand and foot treatment finished neatly with polish.",
    options: [priceOption("Manicure & Pedicure", "IDR 238K"), priceOption("Manicure", "IDR 99K"), priceOption("Pedicure", "IDR 139K"), priceOption("Nail Remover Feet & Hands", "IDR 98K"), priceOption("Nail Gel Feet & Hands", "IDR 438K"), priceOption("Nail Gel Color Feet & Hands", "IDR 138K")],
  },
  {
    id: "waxing",
    name: "Waxing",
    category: "beauty",
    href: "/seminyak/waxing",
    image: "/images/homepage/homepage-24.webp",
    desc: "A professional hair removal treatment using olive oil hot wax for smooth skin.",
    options: [priceOption("Arms", "IDR 159K"), priceOption("Under Arms", "IDR 99K"), priceOption("Back (starting from)", "IDR 139K"), priceOption("Full Back", "IDR 299K"), priceOption("Half Legs", "IDR 149K"), priceOption("Full Legs", "IDR 299K"), priceOption("Waxing Brazilian", "IDR 269K")],
  },
  {
    id: "couple-massage-balinese",
    name: "Couple Massage Balinese",
    category: "couple",
    categories: ["massage", "couple"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-21.webp",
    desc: "A side-by-side massage using steady pressure and flowing movements for shared relaxation.",
    options: [priceOption("1 Hour · 2 pax", "IDR 319K"), priceOption("1.5 Hours · 2 pax", "IDR 479K"), priceOption("2 Hours · 2 pax", "IDR 659K")],
  },
  {
    id: "couple-traditional-massage",
    name: "Couple Traditional Massage",
    category: "couple",
    categories: ["massage", "couple"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-21.webp",
    desc: "A side-by-side massage with firmer pressure to help release tension together.",
    options: [priceOption("1 Hour · 2 pax", "IDR 339K"), priceOption("1.5 Hours · 2 pax", "IDR 519K"), priceOption("2 Hours · 2 pax", "IDR 679K")],
  },
  {
    id: "couple-deep-tissue-massage",
    name: "Couple Deep Tissue Massage",
    category: "couple",
    categories: ["massage", "couple"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-10.webp",
    desc: "A deeper-pressure massage for two, focused on easing tight muscles and improving comfort.",
    options: [priceOption("1 Hour · 2 pax", "IDR 539K"), priceOption("1.5 Hours · 2 pax", "IDR 719K")],
  },
  {
    id: "couple-warm-candle-massage",
    name: "Couple Warm Candle Massage",
    category: "couple",
    categories: ["massage", "couple"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-7.webp",
    desc: "A comforting couple's massage using gently heated candle oils to soften muscles and create a sense of calm.",
    options: [priceOption("1 Hour · 2 pax", "IDR 539K"), priceOption("1.5 Hours · 2 pax", "IDR 799K"), priceOption("2 Hours · 2 pax", "IDR 999K")],
  },
  {
    id: "couple-massage-package-a",
    name: "Couple Massage Package A",
    category: "couple-package",
    categories: ["massage", "couple-package"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-21.webp",
    desc: "A complete couple's massage package combining comfort, balance, and shared relaxation.",
    options: [packageOption("1 Hour Balinese Massage · 2 pax", "IDR 639K", ["30 Minutes Ear Candle"])],
  },
  {
    id: "couple-massage-package-b",
    name: "Couple Massage Package B",
    category: "couple-package",
    categories: ["massage", "couple-package"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-21.webp",
    desc: "A complete couple's massage package combining comfort, balance, and shared relaxation.",
    options: [packageOption("1 Hour Balinese Massage · 2 pax", "IDR 709K", ["1 Hour Bali Moon Facial"])],
  },
  {
    id: "couple-massage-package-c",
    name: "Couple Massage Package C",
    category: "couple-package",
    categories: ["massage", "couple-package"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-7.webp",
    desc: "A complete couple's massage package combining comfort, balance, and shared relaxation.",
    options: [packageOption("1 Hour Warm Candle · 2 pax", "IDR 849K", ["30 Minutes Ear Candle"])],
  },
  {
    id: "couple-massage-package-d",
    name: "Couple Massage Package D",
    category: "couple-package",
    categories: ["massage", "couple-package"],
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-7.webp",
    desc: "A complete couple's massage package combining comfort, balance, and shared relaxation.",
    options: [packageOption("1 Hour Warm Candle · 2 pax", "IDR 929K", ["1 Hour Bali Moon Facial"])],
  },
].sort((a, b) => a.name.localeCompare(b.name));
