const packageOption = (label, price, details) => ({ label, price, details });
const priceOption = (label, price) => ({ label, price });

export const homepageTreatments = [
  {
    name: "Bali Moon Facial",
    href: "/seminyak/bali-moon-facial",
    image: "/images/homepage/homepage-9.webp",
    desc: "A signature facial combining cleansing, exfoliation, facial massage, and a targeted mask to refresh and hydrate the skin.",
    options: [
      packageOption("Package A", "IDR 439K", ["1 Hr Bali Moon Facial", "30 Mins Body Scrub", "1 Hr Balinese Massage"]),
      packageOption("Package B", "IDR 649K", ["1 Hr Bali Moon Facial", "1 Hr Cream Bath", "1 Hr Thai Massage"]),
      packageOption("Package C", "IDR 449K", ["1 Hr Bali Moon Facial", "1 Hr Thai Massage"]),
      packageOption("Package D", "IDR 549K", ["1 Hr Bali Moon Facial", "1 Hr Warm Candle", "30 Mins Body Scrub"]),
    ],
  },
  {
    name: "Balinese Massage",
    href: "/seminyak/balinese-massage",
    image: "/images/homepage/homepage-5.webp",
    desc: "A traditional massage combining acupressure, gentle stretching, skin rolling, and flowing strokes with adjustable pressure.",
    options: [
      packageOption("Package A", "IDR 449K", ["1 Hr Balinese Massage", "1 Hr Medi Pedi", "30 Mins Cream Bath"]),
      packageOption("Package B", "IDR 549K", ["1 Hr Balinese Massage", "1 Hr Medi Pedi", "1 Hr Bali Moon Facial"]),
      packageOption("Package C", "IDR 449K", ["1 Hr Balinese Massage", "30 Mins Cream Bath", "1 Hr Bali Moon Facial"]),
      packageOption("Package D", "IDR 399K", ["1 Hr Balinese Massage", "30 Mins Manicure", "30 Mins Pedicure"]),
    ],
  },
  {
    name: "Body Scrub",
    href: "/seminyak/body-scrub",
    image: "/images/homepage/homepage-13.webp",
    desc: "Natural exfoliation inspired by Balinese lulur rituals to remove buildup and leave the skin feeling smoother and refreshed.",
    options: [
      packageOption("Package A", "IDR 439K", ["30 Mins Body Scrub", "1 Hr Balinese Massage", "1 Hr Bali Moon Facial"]),
      packageOption("Package B", "IDR 449K", ["30 Mins Body Scrub", "1.5 Hr Hot Stone", "30 Mins Head Massage"]),
      packageOption("Package C", "IDR 539K", ["30 Mins Body Scrub", "1 Hr Thai Massage", "1 Hr Cream Bath"]),
      packageOption("Package D", "IDR 549K", ["30 Mins Body Scrub", "1 Hr Warm Candle", "1 Hr Bali Moon Facial"]),
    ],
  },
  {
    name: "Cellulite Massage",
    href: "/seminyak/cellulite-massage",
    image: "/images/homepage/homepage-17.webp",
    desc: "A targeted body treatment using firm, repetitive movements to support circulation, tissue mobility, and smoother-looking skin.",
    options: [
      priceOption("1 Hour", "IDR 350K"),
      priceOption("1.5 Hours", "IDR 450K"),
    ],
  },
  {
    name: "Coconut Oil Massage",
    href: "/seminyak/virgin-coconut-oil-massage",
    image: "/images/homepage/homepage-25.webp",
    desc: "A relaxing massage using pure virgin cold-pressed coconut oil to nourish the skin while easing body tension.",
    options: [
      priceOption("1 Hour", "IDR 300K"),
      priceOption("1.5 Hours", "IDR 440K"),
      priceOption("2 Hours", "IDR 580K"),
    ],
  },
  {
    name: "Couple Massage",
    href: "/seminyak/couple-massage",
    image: "/images/homepage/homepage-21.webp",
    desc: "A shared spa experience where two guests receive personalised treatments side by side with their own therapists.",
    options: [
      packageOption("Package A", "IDR 639K", ["1 Hr Balinese Massage 2 Pax", "30 Mins Ear Candle 2 Pax"]),
      packageOption("Package B", "IDR 709K", ["1 Hr Balinese Massage 2 Pax", "1 Hr Bali Moon Facial 2 Pax"]),
      packageOption("Package C", "IDR 849K", ["1 Hr Warm Candle 2 Pax", "30 Mins Ear Candle 2 Pax"]),
      packageOption("Package D", "IDR 929K", ["1 Hr Warm Candle 2 Pax", "1 Hr Bali Moon Facial 2 Pax"]),
    ],
  },
  {
    name: "Cream Bath",
    href: "/seminyak/hair-creambath",
    image: "/images/homepage/homepage-6.webp",
    desc: "A nourishing Indonesian hair and scalp treatment combining conditioning cream with a gentle, relaxing scalp massage.",
    options: [
      packageOption("Package A", "IDR 649K", ["1 Hr Cream Bath", "1 Hr Thai Massage", "1 Hr Bali Moon Facial"]),
      packageOption("Package B", "IDR 589K", ["1 Hr Cream Bath", "1 Hr Hot Stone", "30 Mins Reflexology"]),
      packageOption("Package C", "IDR 449K", ["30 Mins Cream Bath", "1 Hr Balinese Massage", "1 Hr Bali Moon Facial"]),
      packageOption("Package D", "IDR 539K", ["1 Hr Cream Bath", "1 Hr Thai Massage", "30 Mins Body Scrub"]),
    ],
  },
  {
    name: "Deep Tissue Massage",
    href: "/seminyak/deep-tissue-massage",
    image: "/images/homepage/homepage-10.webp",
    desc: "Slow, firm pressure targets deeper muscle layers and connective tissue to address stiffness and recurring muscle tension.",
    options: [
      priceOption("1 Hour", "IDR 219K"),
      priceOption("1.5 Hours", "IDR 319K"),
    ],
  },
  {
    name: "Ear Candle",
    href: "/seminyak/ear-candle",
    image: "/images/homepage/homepage-14.webp",
    desc: "A traditional wellness treatment combining gentle warmth with light attention around the ears, temples, jaw, and neck.",
    options: [priceOption("30 Minutes", "IDR 159K")],
  },
  {
    name: "Foot Massage",
    href: "/seminyak/foot-massage",
    image: "/images/homepage/homepage-18.webp",
    desc: "A relaxing treatment for the muscles and soft tissues of the feet and lower legs after walking, travel, or prolonged standing.",
    options: [
      priceOption("1 Hour", "IDR 159K"),
      priceOption("1.5 Hours", "IDR 239K"),
      priceOption("2 Hours", "IDR 330K"),
    ],
  },
  {
    name: "Foot Reflexology",
    href: "/seminyak/foot-reflexology",
    image: "/images/homepage/homepage-22.webp",
    desc: "Controlled pressure is applied to structured reflex points on the feet to encourage relaxation and ease tiredness.",
    options: [
      priceOption("30 Minutes", "IDR 99K"),
      priceOption("1 Hour", "IDR 169K"),
      priceOption("1.5 Hours", "IDR 239K"),
    ],
  },
  {
    name: "Hair Braiding",
    href: "/seminyak/hair-braiding",
    image: "/images/homepage/homepage-26.webp",
    desc: "A practical, personalised braided hairstyle designed to keep hair neat and manageable in Bali's warm, humid weather.",
    options: [
      priceOption("Short Hair", "IDR 279K"),
      priceOption("Medium Hair", "IDR 379K"),
      priceOption("Long Hair", "IDR 469K"),
    ],
  },
  {
    name: "Head Massage",
    href: "/seminyak/head-massage",
    image: "/images/homepage/homepage-11.webp",
    desc: "Slow, rhythmic techniques focus on the scalp, temples, neck, and upper shoulders to ease tension and encourage relaxation.",
    options: [
      priceOption("1 Hour", "IDR 159K"),
      priceOption("1.5 Hours", "IDR 239K"),
      priceOption("2 Hours", "IDR 330K"),
    ],
  },
  {
    name: "Hot Stone Massage",
    href: "/seminyak/hot-stone-massage",
    image: "/images/homepage/homepage-7.webp",
    desc: "Smooth heated basalt stones soften tight muscles before massage techniques are applied for deep, comfortable relaxation.",
    options: [
      packageOption("Package A", "IDR 449K", ["1.5 Hr Hot Stone", "30 Mins Body Scrub", "30 Mins Head Massage"]),
      packageOption("Package B", "IDR 559K", ["1 Hr Hot Stone", "1 Hr Cream Bath", "30 Mins Reflexology"]),
      packageOption("Package C", "IDR 489K", ["1 Hr Hot Stone", "1 Hr Bali Moon Facial"]),
      packageOption("Package D", "IDR 439K", ["1.5 Hr Hot Stone", "30 Mins Pedicure"]),
    ],
  },
  {
    name: "Lymphatic Massage",
    href: "/seminyak/lymphatic-massage",
    image: "/images/homepage/homepage-15.webp",
    desc: "Slow, rhythmic techniques encourage natural lymph flow and support a lighter, more balanced feeling throughout the body.",
    options: [
      priceOption("1 Hour", "IDR 300K"),
      priceOption("1.5 Hours", "IDR 440K"),
      priceOption("2 Hours", "IDR 580K"),
    ],
  },
  {
    name: "Manicure Pedicure",
    href: "/seminyak/manicure-pedicure",
    image: "/images/homepage/homepage-19.webp",
    desc: "Professional hand and foot care including nail cleaning, shaping, cuticle care, conditioning, hydration, and polish.",
    options: [
      packageOption("Package A", "IDR 449K", ["1 Hr Mani & Pedi", "1 Hr Balinese Massage", "30 Mins Cream Bath"]),
      packageOption("Package B", "IDR 549K", ["1 Hr Mani & Pedi", "1 Hr Balinese Massage", "1 Hr Bali Moon Facial"]),
      packageOption("Package C", "IDR 299K", ["1 Hr Mani & Pedi", "30 Mins Cream Bath"]),
      packageOption("Package D", "IDR 399K", ["30 Mins Pedicure", "30 Mins Manicure", "1 Hr Balinese Massage"]),
    ],
  },
  {
    name: "Nail Art",
    href: "/seminyak/nail-art",
    image: "/images/homepage/homepage-23.webp",
    desc: "Creative nail colour and gel services with a durable professional finish tailored to your preferred style and occasion.",
    options: [
      priceOption("Manicure & Colour", "IDR 159K"),
      priceOption("Pedicure & Colour", "IDR 169K"),
      priceOption("Nail Gel", "IDR 219K"),
    ],
  },
  {
    name: "Shiatsu Massage",
    href: "/seminyak/shiatsu-massage",
    image: "/images/homepage/homepage-27.webp",
    desc: "Traditional Japanese bodywork using finger, thumb, and palm pressure with gentle stretching instead of long oil strokes.",
    options: [
      priceOption("30 Minutes", "IDR 119K"),
      priceOption("1 Hour", "IDR 219K"),
      priceOption("1.5 Hours", "IDR 329K"),
    ],
  },
  {
    name: "Sports Massage",
    href: "/seminyak/sports-massage",
    image: "/images/homepage/homepage-8.webp",
    desc: "Targeted pressure, stretching, and rhythmic movement support active bodies affected by exercise, surfing, and travel.",
    options: [
      priceOption("1 Hour", "IDR 269K"),
      priceOption("1.5 Hours", "IDR 359K"),
    ],
  },
  {
    name: "Sunburn Treatment",
    href: "/seminyak/sunburn-treatment",
    image: "/images/homepage/homepage-12.webp",
    desc: "Cooling aloe vera and gentle application techniques help calm, rehydrate, and comfort sun-exposed sensitive skin.",
    options: [priceOption("1 Hour", "IDR 199K")],
  },
  {
    name: "Thai Massage",
    href: "/seminyak/thai-massage",
    image: "/images/homepage/homepage-20.webp",
    desc: "Rhythmic pressure, assisted stretching, and controlled movement work together to improve flexibility and ease tension.",
    options: [
      packageOption("Package A", "IDR 549K", ["1 Hr Thai Massage", "1 Hr Bali Moon Facial", "30 Mins Manicure"]),
      packageOption("Package B", "IDR 649K", ["1 Hr Thai Massage", "1 Hr Cream Bath", "1 Hr Bali Moon Facial"]),
      packageOption("Package C", "IDR 449K", ["1 Hr Thai Massage", "1 Hr Bali Moon Facial"]),
      packageOption("Package D", "IDR 539K", ["1 Hr Thai Massage", "1 Hr Cream Bath", "30 Mins Body Scrub"]),
    ],
  },
  {
    name: "Traditional Massage",
    href: "/seminyak/traditional-massage",
    image: "/images/homepage/homepage-16.webp",
    desc: "Firmer pressure, kneading, and focused hands-on techniques release tension in muscles that feel stiff or overworked.",
    options: [
      priceOption("1 Hour", "IDR 169K"),
      priceOption("1.5 Hours", "IDR 259K"),
      priceOption("2 Hours", "IDR 339K"),
    ],
  },
  {
    name: "Waxing",
    href: "/seminyak/waxing",
    image: "/images/homepage/homepage-24.webp",
    desc: "Professional waxing for selected body areas with careful techniques and products chosen for a smooth, clean result.",
    options: [
      priceOption("Arms", "IDR 159K"),
      priceOption("Under Arms", "IDR 99K"),
      priceOption("Back", "IDR 139K"),
      priceOption("Full Back", "IDR 299K"),
      priceOption("Half Legs", "IDR 149K"),
      priceOption("Full Legs", "IDR 299K"),
      priceOption("Waxing Brazilian", "IDR 269K"),
    ],
  },
].sort((a, b) => a.name.localeCompare(b.name));
